# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automation.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_automation(object):
    def setupUi(self, automation):
        automation.setObjectName("automation")
        automation.resize(2072, 1173)
        self.gridLayout_3 = QtWidgets.QGridLayout(automation)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lb_title = QtWidgets.QLabel(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_title.sizePolicy().hasHeightForWidth())
        self.lb_title.setSizePolicy(sizePolicy)
        self.lb_title.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lb_title.setFont(font)
        self.lb_title.setObjectName("lb_title")
        self.gridLayout_3.addWidget(self.lb_title, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(automation)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame2 = QtWidgets.QFrame(self.tab)
        self.frame2.setObjectName("frame2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_loop = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_loop.sizePolicy().hasHeightForWidth())
        self.pb_loop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_loop.setFont(font)
        self.pb_loop.setObjectName("pb_loop")
        self.gridLayout_2.addWidget(self.pb_loop, 5, 1, 1, 1)
        self.pb_pressp = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_pressp.sizePolicy().hasHeightForWidth())
        self.pb_pressp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_pressp.setFont(font)
        self.pb_pressp.setObjectName("pb_pressp")
        self.gridLayout_2.addWidget(self.pb_pressp, 4, 1, 1, 1)
        self.pb_dutin = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dutin.sizePolicy().hasHeightForWidth())
        self.pb_dutin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_dutin.setFont(font)
        self.pb_dutin.setObjectName("pb_dutin")
        self.gridLayout_2.addWidget(self.pb_dutin, 3, 0, 1, 1)
        self.pb_single = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_single.sizePolicy().hasHeightForWidth())
        self.pb_single.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_single.setFont(font)
        self.pb_single.setObjectName("pb_single")
        self.gridLayout_2.addWidget(self.pb_single, 5, 0, 1, 1)
        self.pb_cyair2 = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_cyair2.sizePolicy().hasHeightForWidth())
        self.pb_cyair2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_cyair2.setFont(font)
        self.pb_cyair2.setObjectName("pb_cyair2")
        self.gridLayout_2.addWidget(self.pb_cyair2, 2, 1, 1, 1)
        self.pb_clear = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_clear.sizePolicy().hasHeightForWidth())
        self.pb_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_clear.setFont(font)
        self.pb_clear.setObjectName("pb_clear")
        self.gridLayout_2.addWidget(self.pb_clear, 6, 1, 1, 1)
        self.pb_initp = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_initp.sizePolicy().hasHeightForWidth())
        self.pb_initp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_initp.setFont(font)
        self.pb_initp.setObjectName("pb_initp")
        self.gridLayout_2.addWidget(self.pb_initp, 4, 0, 1, 1)
        self.cb_door = QtWidgets.QCheckBox(self.frame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_door.setFont(font)
        self.cb_door.setObjectName("cb_door")
        self.gridLayout_2.addWidget(self.cb_door, 0, 1, 1, 1)
        self.pb_cyair1 = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_cyair1.sizePolicy().hasHeightForWidth())
        self.pb_cyair1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_cyair1.setFont(font)
        self.pb_cyair1.setObjectName("pb_cyair1")
        self.gridLayout_2.addWidget(self.pb_cyair1, 2, 0, 1, 1)
        self.cb_light = QtWidgets.QCheckBox(self.frame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_light.setFont(font)
        self.cb_light.setObjectName("cb_light")
        self.gridLayout_2.addWidget(self.cb_light, 1, 0, 1, 1)
        self.cb_manual = QtWidgets.QCheckBox(self.frame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_manual.setFont(font)
        self.cb_manual.setObjectName("cb_manual")
        self.gridLayout_2.addWidget(self.cb_manual, 0, 0, 1, 1)
        self.pb_dutout = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dutout.sizePolicy().hasHeightForWidth())
        self.pb_dutout.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_dutout.setFont(font)
        self.pb_dutout.setObjectName("pb_dutout")
        self.gridLayout_2.addWidget(self.pb_dutout, 3, 1, 1, 1)
        self.pb_loopstop = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_loopstop.sizePolicy().hasHeightForWidth())
        self.pb_loopstop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_loopstop.setFont(font)
        self.pb_loopstop.setObjectName("pb_loopstop")
        self.gridLayout_2.addWidget(self.pb_loopstop, 6, 0, 1, 1)
        self.cb_daq = QtWidgets.QCheckBox(self.frame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_daq.setFont(font)
        self.cb_daq.setObjectName("cb_daq")
        self.gridLayout_2.addWidget(self.cb_daq, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame2, 0, 2, 1, 1)
        self.frame1 = QtWidgets.QFrame(self.tab)
        self.frame1.setObjectName("frame1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lb_rts_2 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_rts_2.setFont(font)
        self.lb_rts_2.setObjectName("lb_rts_2")
        self.gridLayout_6.addWidget(self.lb_rts_2, 8, 2, 1, 1)
        self.lb_rtp_3 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_rtp_3.setFont(font)
        self.lb_rtp_3.setObjectName("lb_rtp_3")
        self.gridLayout_6.addWidget(self.lb_rtp_3, 7, 4, 1, 1)
        self.dsb_rtsx = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_rtsx.sizePolicy().hasHeightForWidth())
        self.dsb_rtsx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_rtsx.setFont(font)
        self.dsb_rtsx.setReadOnly(True)
        self.dsb_rtsx.setMaximum(10000.0)
        self.dsb_rtsx.setObjectName("dsb_rtsx")
        self.gridLayout_6.addWidget(self.dsb_rtsx, 8, 1, 1, 1)
        self.lb_rts = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_rts.setFont(font)
        self.lb_rts.setObjectName("lb_rts")
        self.gridLayout_6.addWidget(self.lb_rts, 8, 0, 1, 1)
        self.dsb_rtpz = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_rtpz.sizePolicy().hasHeightForWidth())
        self.dsb_rtpz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_rtpz.setFont(font)
        self.dsb_rtpz.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.dsb_rtpz.setReadOnly(True)
        self.dsb_rtpz.setMaximum(10000.0)
        self.dsb_rtpz.setObjectName("dsb_rtpz")
        self.gridLayout_6.addWidget(self.dsb_rtpz, 7, 5, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cb_zerox = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_zerox.sizePolicy().hasHeightForWidth())
        self.cb_zerox.setSizePolicy(sizePolicy)
        self.cb_zerox.setObjectName("cb_zerox")
        self.gridLayout.addWidget(self.cb_zerox, 0, 0, 1, 1)
        self.cb_limit1x = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limit1x.sizePolicy().hasHeightForWidth())
        self.cb_limit1x.setSizePolicy(sizePolicy)
        self.cb_limit1x.setObjectName("cb_limit1x")
        self.gridLayout.addWidget(self.cb_limit1x, 0, 1, 1, 1)
        self.cb_limit2x = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limit2x.sizePolicy().hasHeightForWidth())
        self.cb_limit2x.setSizePolicy(sizePolicy)
        self.cb_limit2x.setObjectName("cb_limit2x")
        self.gridLayout.addWidget(self.cb_limit2x, 0, 2, 1, 1)
        self.cb_zeroy = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_zeroy.sizePolicy().hasHeightForWidth())
        self.cb_zeroy.setSizePolicy(sizePolicy)
        self.cb_zeroy.setObjectName("cb_zeroy")
        self.gridLayout.addWidget(self.cb_zeroy, 0, 3, 1, 1)
        self.cb_limit1y = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limit1y.sizePolicy().hasHeightForWidth())
        self.cb_limit1y.setSizePolicy(sizePolicy)
        self.cb_limit1y.setObjectName("cb_limit1y")
        self.gridLayout.addWidget(self.cb_limit1y, 0, 4, 1, 1)
        self.cb_limit2y = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limit2y.sizePolicy().hasHeightForWidth())
        self.cb_limit2y.setSizePolicy(sizePolicy)
        self.cb_limit2y.setObjectName("cb_limit2y")
        self.gridLayout.addWidget(self.cb_limit2y, 0, 5, 1, 1)
        self.cb_zeroz = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_zeroz.sizePolicy().hasHeightForWidth())
        self.cb_zeroz.setSizePolicy(sizePolicy)
        self.cb_zeroz.setObjectName("cb_zeroz")
        self.gridLayout.addWidget(self.cb_zeroz, 0, 6, 1, 1)
        self.cb_limit1z = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limit1z.sizePolicy().hasHeightForWidth())
        self.cb_limit1z.setSizePolicy(sizePolicy)
        self.cb_limit1z.setObjectName("cb_limit1z")
        self.gridLayout.addWidget(self.cb_limit1z, 0, 7, 1, 1)
        self.cb_limit2z = QtWidgets.QCheckBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limit2z.sizePolicy().hasHeightForWidth())
        self.cb_limit2z.setSizePolicy(sizePolicy)
        self.cb_limit2z.setObjectName("cb_limit2z")
        self.gridLayout.addWidget(self.cb_limit2z, 0, 8, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 11, 0, 1, 6)
        self.lb_rtp_2 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_rtp_2.setFont(font)
        self.lb_rtp_2.setObjectName("lb_rtp_2")
        self.gridLayout_6.addWidget(self.lb_rtp_2, 7, 2, 1, 1)
        self.dsb_rtpx = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_rtpx.sizePolicy().hasHeightForWidth())
        self.dsb_rtpx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_rtpx.setFont(font)
        self.dsb_rtpx.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.dsb_rtpx.setReadOnly(True)
        self.dsb_rtpx.setMaximum(10000.0)
        self.dsb_rtpx.setObjectName("dsb_rtpx")
        self.gridLayout_6.addWidget(self.dsb_rtpx, 7, 1, 1, 1)
        self.lb_rtp = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_rtp.setFont(font)
        self.lb_rtp.setObjectName("lb_rtp")
        self.gridLayout_6.addWidget(self.lb_rtp, 7, 0, 1, 1)
        self.dsb_rtpy = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_rtpy.sizePolicy().hasHeightForWidth())
        self.dsb_rtpy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_rtpy.setFont(font)
        self.dsb_rtpy.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.dsb_rtpy.setReadOnly(True)
        self.dsb_rtpy.setMaximum(10000.0)
        self.dsb_rtpy.setObjectName("dsb_rtpy")
        self.gridLayout_6.addWidget(self.dsb_rtpy, 7, 3, 1, 1)
        self.pb_x1 = QtWidgets.QPushButton(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_x1.sizePolicy().hasHeightForWidth())
        self.pb_x1.setSizePolicy(sizePolicy)
        self.pb_x1.setObjectName("pb_x1")
        self.gridLayout_6.addWidget(self.pb_x1, 1, 2, 1, 1)
        self.pb_y1 = QtWidgets.QPushButton(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_y1.sizePolicy().hasHeightForWidth())
        self.pb_y1.setSizePolicy(sizePolicy)
        self.pb_y1.setObjectName("pb_y1")
        self.gridLayout_6.addWidget(self.pb_y1, 2, 1, 1, 1)
        self.lb_manuals = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_manuals.setFont(font)
        self.lb_manuals.setObjectName("lb_manuals")
        self.gridLayout_6.addWidget(self.lb_manuals, 9, 0, 1, 1)
        self.dsb_rtsz = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_rtsz.sizePolicy().hasHeightForWidth())
        self.dsb_rtsz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_rtsz.setFont(font)
        self.dsb_rtsz.setReadOnly(True)
        self.dsb_rtsz.setMaximum(10000.0)
        self.dsb_rtsz.setObjectName("dsb_rtsz")
        self.gridLayout_6.addWidget(self.dsb_rtsz, 8, 5, 1, 1)
        self.dsb_manualsx = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_manualsx.sizePolicy().hasHeightForWidth())
        self.dsb_manualsx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_manualsx.setFont(font)
        self.dsb_manualsx.setReadOnly(True)
        self.dsb_manualsx.setMaximum(10000.0)
        self.dsb_manualsx.setObjectName("dsb_manualsx")
        self.gridLayout_6.addWidget(self.dsb_manualsx, 9, 1, 1, 1)
        self.dsb_rtsy = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_rtsy.sizePolicy().hasHeightForWidth())
        self.dsb_rtsy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_rtsy.setFont(font)
        self.dsb_rtsy.setReadOnly(True)
        self.dsb_rtsy.setMaximum(10000.0)
        self.dsb_rtsy.setObjectName("dsb_rtsy")
        self.gridLayout_6.addWidget(self.dsb_rtsy, 8, 3, 1, 1)
        self.lb_rts_3 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_rts_3.setFont(font)
        self.lb_rts_3.setObjectName("lb_rts_3")
        self.gridLayout_6.addWidget(self.lb_rts_3, 8, 4, 1, 1)
        self.pb_xhome = QtWidgets.QPushButton(self.frame1)
        self.pb_xhome.setObjectName("pb_xhome")
        self.gridLayout_6.addWidget(self.pb_xhome, 0, 3, 1, 1)
        self.pb_zhome = QtWidgets.QPushButton(self.frame1)
        self.pb_zhome.setObjectName("pb_zhome")
        self.gridLayout_6.addWidget(self.pb_zhome, 1, 5, 1, 1)
        self.dsb_manualsz = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_manualsz.sizePolicy().hasHeightForWidth())
        self.dsb_manualsz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_manualsz.setFont(font)
        self.dsb_manualsz.setReadOnly(True)
        self.dsb_manualsz.setMaximum(10000.0)
        self.dsb_manualsz.setObjectName("dsb_manualsz")
        self.gridLayout_6.addWidget(self.dsb_manualsz, 9, 5, 1, 1)
        self.dsb_autosx = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_autosx.sizePolicy().hasHeightForWidth())
        self.dsb_autosx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_autosx.setFont(font)
        self.dsb_autosx.setReadOnly(True)
        self.dsb_autosx.setMaximum(10000.0)
        self.dsb_autosx.setObjectName("dsb_autosx")
        self.gridLayout_6.addWidget(self.dsb_autosx, 10, 1, 1, 1)
        self.lb_manuals_2 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_manuals_2.setFont(font)
        self.lb_manuals_2.setObjectName("lb_manuals_2")
        self.gridLayout_6.addWidget(self.lb_manuals_2, 9, 2, 1, 1)
        self.lb_manuals_3 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_manuals_3.setFont(font)
        self.lb_manuals_3.setObjectName("lb_manuals_3")
        self.gridLayout_6.addWidget(self.lb_manuals_3, 9, 4, 1, 1)
        self.lb_autos = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_autos.setFont(font)
        self.lb_autos.setObjectName("lb_autos")
        self.gridLayout_6.addWidget(self.lb_autos, 10, 0, 1, 1)
        self.dsb_manualsy = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_manualsy.sizePolicy().hasHeightForWidth())
        self.dsb_manualsy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_manualsy.setFont(font)
        self.dsb_manualsy.setReadOnly(True)
        self.dsb_manualsy.setMaximum(10000.0)
        self.dsb_manualsy.setObjectName("dsb_manualsy")
        self.gridLayout_6.addWidget(self.dsb_manualsy, 9, 3, 1, 1)
        self.pb_yhome = QtWidgets.QPushButton(self.frame1)
        self.pb_yhome.setObjectName("pb_yhome")
        self.gridLayout_6.addWidget(self.pb_yhome, 2, 3, 1, 1)
        self.lb_autos_3 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_autos_3.setFont(font)
        self.lb_autos_3.setObjectName("lb_autos_3")
        self.gridLayout_6.addWidget(self.lb_autos_3, 10, 4, 1, 1)
        self.lb_autos_2 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_autos_2.setFont(font)
        self.lb_autos_2.setObjectName("lb_autos_2")
        self.gridLayout_6.addWidget(self.lb_autos_2, 10, 2, 1, 1)
        self.dsb_autosz = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_autosz.sizePolicy().hasHeightForWidth())
        self.dsb_autosz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_autosz.setFont(font)
        self.dsb_autosz.setReadOnly(True)
        self.dsb_autosz.setMaximum(10000.0)
        self.dsb_autosz.setObjectName("dsb_autosz")
        self.gridLayout_6.addWidget(self.dsb_autosz, 10, 5, 1, 1)
        self.lb_ypos = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_ypos.setFont(font)
        self.lb_ypos.setObjectName("lb_ypos")
        self.gridLayout_6.addWidget(self.lb_ypos, 4, 0, 1, 1)
        self.lb_xpos = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_xpos.setFont(font)
        self.lb_xpos.setObjectName("lb_xpos")
        self.gridLayout_6.addWidget(self.lb_xpos, 3, 0, 1, 1)
        self.dsb_autosy = QtWidgets.QDoubleSpinBox(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_autosy.sizePolicy().hasHeightForWidth())
        self.dsb_autosy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_autosy.setFont(font)
        self.dsb_autosy.setReadOnly(True)
        self.dsb_autosy.setMaximum(10000.0)
        self.dsb_autosy.setObjectName("dsb_autosy")
        self.gridLayout_6.addWidget(self.dsb_autosy, 10, 3, 1, 1)
        self.pb_z1 = QtWidgets.QPushButton(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_z1.sizePolicy().hasHeightForWidth())
        self.pb_z1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_z1.setFont(font)
        self.pb_z1.setObjectName("pb_z1")
        self.gridLayout_6.addWidget(self.pb_z1, 2, 4, 1, 1)
        self.pb_x2 = QtWidgets.QPushButton(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_x2.sizePolicy().hasHeightForWidth())
        self.pb_x2.setSizePolicy(sizePolicy)
        self.pb_x2.setObjectName("pb_x2")
        self.gridLayout_6.addWidget(self.pb_x2, 1, 0, 1, 1)
        self.pb_xrun = QtWidgets.QPushButton(self.frame1)
        self.pb_xrun.setObjectName("pb_xrun")
        self.gridLayout_6.addWidget(self.pb_xrun, 3, 3, 1, 1)
        self.pb_z2 = QtWidgets.QPushButton(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_z2.sizePolicy().hasHeightForWidth())
        self.pb_z2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_z2.setFont(font)
        self.pb_z2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pb_z2.setObjectName("pb_z2")
        self.gridLayout_6.addWidget(self.pb_z2, 0, 4, 1, 1)
        self.pb_y2 = QtWidgets.QPushButton(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_y2.sizePolicy().hasHeightForWidth())
        self.pb_y2.setSizePolicy(sizePolicy)
        self.pb_y2.setObjectName("pb_y2")
        self.gridLayout_6.addWidget(self.pb_y2, 0, 1, 1, 1)
        self.lb_zpos = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_zpos.setFont(font)
        self.lb_zpos.setObjectName("lb_zpos")
        self.gridLayout_6.addWidget(self.lb_zpos, 5, 0, 1, 1)
        self.dsb_zpos = QtWidgets.QDoubleSpinBox(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_zpos.setFont(font)
        self.dsb_zpos.setMaximum(99999.99)
        self.dsb_zpos.setObjectName("dsb_zpos")
        self.gridLayout_6.addWidget(self.dsb_zpos, 5, 1, 1, 1)
        self.pb_yrun = QtWidgets.QPushButton(self.frame1)
        self.pb_yrun.setObjectName("pb_yrun")
        self.gridLayout_6.addWidget(self.pb_yrun, 4, 3, 1, 1)
        self.dsb_xpos = QtWidgets.QDoubleSpinBox(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_xpos.setFont(font)
        self.dsb_xpos.setMaximum(99999.99)
        self.dsb_xpos.setObjectName("dsb_xpos")
        self.gridLayout_6.addWidget(self.dsb_xpos, 3, 1, 1, 1)
        self.pb_zrun = QtWidgets.QPushButton(self.frame1)
        self.pb_zrun.setObjectName("pb_zrun")
        self.gridLayout_6.addWidget(self.pb_zrun, 5, 3, 1, 1)
        self.dsb_ypos = QtWidgets.QDoubleSpinBox(self.frame1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_ypos.setFont(font)
        self.dsb_ypos.setMaximum(99999.99)
        self.dsb_ypos.setObjectName("dsb_ypos")
        self.gridLayout_6.addWidget(self.dsb_ypos, 4, 1, 1, 1)
        self.lb_space = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_space.sizePolicy().hasHeightForWidth())
        self.lb_space.setSizePolicy(sizePolicy)
        self.lb_space.setText("")
        self.lb_space.setObjectName("lb_space")
        self.gridLayout_6.addWidget(self.lb_space, 6, 0, 1, 1)
        self.pb_clearerror = QtWidgets.QPushButton(self.frame1)
        self.pb_clearerror.setObjectName("pb_clearerror")
        self.gridLayout_6.addWidget(self.pb_clearerror, 4, 5, 1, 1)
        self.gridLayout_4.addWidget(self.frame1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lb_para1 = QtWidgets.QLabel(self.tab_2)
        self.lb_para1.setObjectName("lb_para1")
        self.gridLayout_5.addWidget(self.lb_para1, 0, 0, 1, 1)
        self.pb_save1 = QtWidgets.QPushButton(self.tab_2)
        self.pb_save1.setObjectName("pb_save1")
        self.gridLayout_5.addWidget(self.pb_save1, 0, 1, 1, 1)
        self.lb_para2 = QtWidgets.QLabel(self.tab_2)
        self.lb_para2.setObjectName("lb_para2")
        self.gridLayout_5.addWidget(self.lb_para2, 0, 2, 1, 1)
        self.pb_save2 = QtWidgets.QPushButton(self.tab_2)
        self.pb_save2.setObjectName("pb_save2")
        self.gridLayout_5.addWidget(self.pb_save2, 0, 3, 1, 1)
        self.lb_para3 = QtWidgets.QLabel(self.tab_2)
        self.lb_para3.setObjectName("lb_para3")
        self.gridLayout_5.addWidget(self.lb_para3, 0, 4, 1, 1)
        self.pb_save3 = QtWidgets.QPushButton(self.tab_2)
        self.pb_save3.setObjectName("pb_save3")
        self.gridLayout_5.addWidget(self.pb_save3, 0, 5, 1, 1)
        self.tw_para1 = QtWidgets.QTableWidget(self.tab_2)
        self.tw_para1.setObjectName("tw_para1")
        self.tw_para1.setColumnCount(0)
        self.tw_para1.setRowCount(0)
        self.gridLayout_5.addWidget(self.tw_para1, 1, 0, 1, 2)
        self.tw_para2 = QtWidgets.QTableWidget(self.tab_2)
        self.tw_para2.setObjectName("tw_para2")
        self.tw_para2.setColumnCount(0)
        self.tw_para2.setRowCount(0)
        self.gridLayout_5.addWidget(self.tw_para2, 1, 2, 1, 2)
        self.tw_para3 = QtWidgets.QTableWidget(self.tab_2)
        self.tw_para3.setObjectName("tw_para3")
        self.tw_para3.setColumnCount(0)
        self.tw_para3.setRowCount(0)
        self.gridLayout_5.addWidget(self.tw_para3, 1, 4, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.calpos1X = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos1X.setObjectName("calpos1X")
        self.gridLayout_7.addWidget(self.calpos1X, 1, 1, 1, 1)
        self.calpos1Y = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos1Y.setObjectName("calpos1Y")
        self.gridLayout_7.addWidget(self.calpos1Y, 1, 2, 1, 1)
        self.calpos1F = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos1F.setObjectName("calpos1F")
        self.gridLayout_7.addWidget(self.calpos1F, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 2, 0, 1, 1)
        self.calpos2X = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos2X.setObjectName("calpos2X")
        self.gridLayout_7.addWidget(self.calpos2X, 2, 1, 1, 1)
        self.calpos2Y = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos2Y.setObjectName("calpos2Y")
        self.gridLayout_7.addWidget(self.calpos2Y, 2, 2, 1, 1)
        self.calpos2F = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos2F.setObjectName("calpos2F")
        self.gridLayout_7.addWidget(self.calpos2F, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 3, 0, 1, 1)
        self.calpos3X = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos3X.setObjectName("calpos3X")
        self.gridLayout_7.addWidget(self.calpos3X, 3, 1, 1, 1)
        self.calpos3Y = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos3Y.setObjectName("calpos3Y")
        self.gridLayout_7.addWidget(self.calpos3Y, 3, 2, 1, 1)
        self.calpos3F = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos3F.setObjectName("calpos3F")
        self.gridLayout_7.addWidget(self.calpos3F, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 4, 0, 1, 1)
        self.calpos4X = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos4X.setObjectName("calpos4X")
        self.gridLayout_7.addWidget(self.calpos4X, 4, 1, 1, 1)
        self.calpos4Y = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos4Y.setObjectName("calpos4Y")
        self.gridLayout_7.addWidget(self.calpos4Y, 4, 2, 1, 1)
        self.calpos4F = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.calpos4F.setObjectName("calpos4F")
        self.gridLayout_7.addWidget(self.calpos4F, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 5, 0, 1, 1)
        self.caneraposX = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.caneraposX.setObjectName("caneraposX")
        self.gridLayout_7.addWidget(self.caneraposX, 5, 1, 1, 1)
        self.cameraposY = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.cameraposY.setObjectName("cameraposY")
        self.gridLayout_7.addWidget(self.cameraposY, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 6, 0, 1, 1)
        self.markX = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.markX.setObjectName("markX")
        self.gridLayout_7.addWidget(self.markX, 6, 1, 1, 1)
        self.markY = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.markY.setObjectName("markY")
        self.gridLayout_7.addWidget(self.markY, 6, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 7, 0, 1, 1)
        self.headX = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.headX.setObjectName("headX")
        self.gridLayout_7.addWidget(self.headX, 7, 1, 1, 1)
        self.headY = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.headY.setObjectName("headY")
        self.gridLayout_7.addWidget(self.headY, 7, 2, 1, 1)
        self.pb_sensorcal = QtWidgets.QPushButton(self.tab_3)
        self.pb_sensorcal.setObjectName("pb_sensorcal")
        self.gridLayout_7.addWidget(self.pb_sensorcal, 7, 4, 1, 1)
        self.pb_cameracal = QtWidgets.QPushButton(self.tab_3)
        self.pb_cameracal.setObjectName("pb_cameracal")
        self.gridLayout_7.addWidget(self.pb_cameracal, 7, 5, 1, 1)
        self.lb_imagecal = QtWidgets.QLabel(self.tab_3)
        self.lb_imagecal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lb_imagecal.setText("")
        self.lb_imagecal.setObjectName("lb_imagecal")
        self.gridLayout_7.addWidget(self.lb_imagecal, 0, 4, 6, 2)
        self.gridLayout_7.setColumnStretch(0, 2)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.gridLayout_7.setColumnStretch(2, 2)
        self.gridLayout_7.setColumnStretch(3, 2)
        self.gridLayout_7.setColumnStretch(4, 3)
        self.gridLayout_7.setColumnStretch(5, 3)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(automation)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(automation)

    def retranslateUi(self, automation):
        _translate = QtCore.QCoreApplication.translate
        automation.setWindowTitle(_translate("automation", "Automation"))
        self.lb_title.setText(_translate("automation", "Automation"))
        self.pb_loop.setText(_translate("automation", "循环按压"))
        self.pb_pressp.setText(_translate("automation", "Z打键位"))
        self.pb_dutin.setText(_translate("automation", "手动进料"))
        self.pb_single.setText(_translate("automation", "单次按压"))
        self.pb_cyair2.setText(_translate("automation", "吸真空-松"))
        self.pb_clear.setText(_translate("automation", "计数复位"))
        self.pb_initp.setText(_translate("automation", "Z初始位"))
        self.cb_door.setText(_translate("automation", "屏蔽安全门"))
        self.pb_cyair1.setText(_translate("automation", "吸真空-吸"))
        self.cb_light.setText(_translate("automation", "照明"))
        self.cb_manual.setText(_translate("automation", "手动模式"))
        self.pb_dutout.setText(_translate("automation", "手动出料"))
        self.pb_loopstop.setText(_translate("automation", "循环停止"))
        self.cb_daq.setText(_translate("automation", "DAQ"))
        self.lb_rts_2.setText(_translate("automation", "Y实时速度:"))
        self.lb_rtp_3.setText(_translate("automation", "Z实时位置:"))
        self.lb_rts.setText(_translate("automation", "X实时速度:"))
        self.cb_zerox.setText(_translate("automation", "Zero"))
        self.cb_limit1x.setText(_translate("automation", "Limit+"))
        self.cb_limit2x.setText(_translate("automation", "Limit-"))
        self.cb_zeroy.setText(_translate("automation", "Zero"))
        self.cb_limit1y.setText(_translate("automation", "Limit+"))
        self.cb_limit2y.setText(_translate("automation", "Limit-"))
        self.cb_zeroz.setText(_translate("automation", "Zero"))
        self.cb_limit1z.setText(_translate("automation", "Limit+"))
        self.cb_limit2z.setText(_translate("automation", "Limit-"))
        self.lb_rtp_2.setText(_translate("automation", "Y实时位置:"))
        self.lb_rtp.setText(_translate("automation", "X实时位置:"))
        self.pb_x1.setText(_translate("automation", "X+"))
        self.pb_y1.setText(_translate("automation", "Y+"))
        self.lb_manuals.setText(_translate("automation", "X手动速度:"))
        self.lb_rts_3.setText(_translate("automation", "Z实时速度:"))
        self.pb_xhome.setText(_translate("automation", "X Home"))
        self.pb_zhome.setText(_translate("automation", "Z Home"))
        self.lb_manuals_2.setText(_translate("automation", "Y手动速度:"))
        self.lb_manuals_3.setText(_translate("automation", "Z手动速度:"))
        self.lb_autos.setText(_translate("automation", "X自动速度:"))
        self.pb_yhome.setText(_translate("automation", "Y Home"))
        self.lb_autos_3.setText(_translate("automation", "Z自动速度:"))
        self.lb_autos_2.setText(_translate("automation", "Y自动速度:"))
        self.lb_ypos.setText(_translate("automation", "Y绝对位置"))
        self.lb_xpos.setText(_translate("automation", "X绝对位置"))
        self.pb_z1.setText(_translate("automation", "Z+"))
        self.pb_x2.setText(_translate("automation", "X-"))
        self.pb_xrun.setText(_translate("automation", "X Run"))
        self.pb_z2.setText(_translate("automation", "Z-"))
        self.pb_y2.setText(_translate("automation", "Y-"))
        self.lb_zpos.setText(_translate("automation", "Z绝对位置"))
        self.pb_yrun.setText(_translate("automation", "Y Run"))
        self.pb_zrun.setText(_translate("automation", "Z Run"))
        self.pb_clearerror.setText(_translate("automation", "ClearError"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("automation", "手动调试"))
        self.lb_para1.setText(_translate("automation", "轴参数："))
        self.pb_save1.setText(_translate("automation", "保存"))
        self.lb_para2.setText(_translate("automation", "按压参数："))
        self.pb_save2.setText(_translate("automation", "保存"))
        self.lb_para3.setText(_translate("automation", "坐标参数："))
        self.pb_save3.setText(_translate("automation", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("automation", "参数设置"))
        self.label.setText(_translate("automation", "X"))
        self.label_2.setText(_translate("automation", "Y"))
        self.label_3.setText(_translate("automation", "Force"))
        self.label_5.setText(_translate("automation", "校准位1"))
        self.label_6.setText(_translate("automation", "校准位2"))
        self.label_7.setText(_translate("automation", "校准位3"))
        self.label_8.setText(_translate("automation", "校准位4"))
        self.label_9.setText(_translate("automation", "相机位置："))
        self.label_10.setText(_translate("automation", "基准点位置："))
        self.label_11.setText(_translate("automation", "打头位置："))
        self.pb_sensorcal.setText(_translate("automation", "SensorCalibration"))
        self.pb_cameracal.setText(_translate("automation", "CameraCalibration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("automation", "校准"))

